
export const ErrorCodeEnum = {
  // ===== AUTHENTICATION & AUTHORIZATION =====
  ACCESS_UNAUTHORIZED: 'ACCESS_UNAUTHORIZED',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_UNAUTHORIZED_ACCESS: 'AUTH_UNAUTHORIZED_ACCESS',
  AUTH_TOKEN_NOT_FOUND: 'AUTH_TOKEN_NOT_FOUND',

  // ===== VALIDATION & REQUEST ERRORS =====
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELDS: 'MISSING_REQUIRED_FIELDS',

  // ===== RESOURCE & BUSINESS LOGIC ERRORS =====
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  INSUFFICIENT_COINS: 'INSUFFICIENT_COINS',
  WHEEL_NOT_FOUND: 'WHEEL_NOT_FOUND',
  WHEEL_ALREADY_ACTIVE: 'WHEEL_ALREADY_ACTIVE',
  WHEEL_NOT_JOINABLE: 'WHEEL_NOT_JOINABLE',
  WHEEL_NOT_STARTABLE: 'WHEEL_NOT_STARTABLE',
  NOT_ENOUGH_PARTICIPANTS: 'NOT_ENOUGH_PARTICIPANTS',

  // ===== GAME / TRANSACTION ERRORS =====
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  REFUND_FAILED: 'REFUND_FAILED',
  PAYOUT_FAILED: 'PAYOUT_FAILED',
  CONFIG_MISSING: 'CONFIG_MISSING',

  // ===== SYSTEM & SERVER ERRORS =====
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  SOCKET_CONNECTION_ERROR: 'SOCKET_CONNECTION_ERROR',
} as const;

// Type union of the enum *values*
export type ErrorCodeEnumType = typeof ErrorCodeEnum[keyof typeof ErrorCodeEnum];
